language: python
python:
  - "3.7"
services:
  - postgresql
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - createdb test_db
# command to run tests
script:
  - pytest