language: python
python:
- '3.7'
services:
- postgresql
- docker

env:
  global:
    DOCKER_REPO=brunoribca/workflow-mq

install:
- python setup.py install
before_script:
- createdb test_db
script:
- export $(cat .env)
- python manage.py test
- docker build -t $DOCKER_REPO .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master